### ISSUE TITLE
Comparison with TopFormer

### ISSUE THREAD

**Issue by ofirkris** [xinyu-laura/MMUDA#1]
Hello, great work with this project.
Can you please show a comparison to TopFormer which was cited in your paper comparing iOU, flops and number of parameters?

**Comment by xinyu-laura** [comment]
TopFormer is mainly designed for Mobile Semantic Segmentation, which is not the same as the goal of our model. If you’re interested, the dataset for evaluation can be found here: https://github.com/jamycheung/ISSAFE.
