### ISSUE TITLE
Strip pooling

### ISSUE THREAD

**Issue by kaigelee** [xinyu-laura/MMUDA#2]
没有找到关于Strip pooling的实现？
请问能指引一下吗？感谢

**Comment by xinyu-laura** [comment]
您好，整理代码的时候忘记把Strip pooling这一部分加进去了，如有需要，下面是striping pooling的实现：
pool_1 = nn.AdaptiveAvgPool2d((1, None))
conv_1 = nn.Sequential(nn.Conv2d(inter_channels, inter_channels, (1, 3), 1, (0, 1), bias=False),norm_layer(inter_channels))
pool_2 = nn.AdaptiveAvgPool2d((None, 1))
conv_2 = nn.Sequential(nn.Conv2d(inter_channels, inter_channels, (3, 1), 1, (1, 0), bias=False),norm_layer(inter_channels))
conv_sp = nn.Sequential(nn.Conv2d(inter_channels, inter_channels, 3, 1, 1, bias=False),norm_layer(inter_channels),nn.ReLU(True))

sp_1 = F.interpolate(conv_1(pool_1(x)), (h, w), **self._up_kwargs)
sp_2 = F.interpolate(conv_2(pool_2(x)), (h, w), **self._up_kwargs)
out = conv_sp(F.relu_(sp_1 + sp_2))
